db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/Control_Work_04_04_26
db.username=postgres
db.password=Almazcuzel2006
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true