DROP TABLE IF EXISTS lead_requests;
DROP TABLE IF EXISTS option_items;
DROP TABLE IF EXISTS trim_levels;
DROP TABLE IF EXISTS car_models;

CREATE TABLE car_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    base_price DECIMAL(12, 2) NOT NULL,
    image_url VARCHAR(255) NOT NULL
);

CREATE TABLE trim_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(400) NOT NULL,
    extra_price DECIMAL(12, 2) NOT NULL,
    car_model_id BIGINT NOT NULL,
    CONSTRAINT fk_trim_model FOREIGN KEY (car_model_id) REFERENCES car_models(id)
);

CREATE TABLE option_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    trim_level_id BIGINT NOT NULL,
    CONSTRAINT fk_option_trim FOREIGN KEY (trim_level_id) REFERENCES trim_levels(id)
);

CREATE TABLE lead_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(50) NOT NULL,
    page_source VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);
